name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # This ensures it runs on GitHub's Windows hosted runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild HighFPSFix.sln /p:Configuration=Release
