name: Build Project

on:
  push:
    branches:
      - main  # You can change this if you're working with another branch

jobs:
  build:
    runs-on: windows-latest  # This will use a Windows runner for building the project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This step checks out your code

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1  # This sets up MSBuild to build the solution

      - name: Build solution
        run: msbuild HighFPSFix.sln /p:Configuration=Release  # This command builds the solution in Release mode
